# Generated by Django 4.2.19 on 2025-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='skin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='file',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='title',
        ),
    ]
