# Generated by Django 4.2.19 on 2025-05-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_remove_skin_created_at_remove_skin_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='artist',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skin',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
