# Generated by Django 4.2.19 on 2025-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skin_artist_skin_description_skin_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='skin',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
